[supervisord]
nodaemon=true
logfile=/dev/stdout
logfile_maxbytes=0

[program:http]
command=python -c "from service import run_http; run_http()"
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:grpc]
command=python -c "from service import run_grpc; run_grpc()"
directory=/app
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
